Add documentation for #5806
napari/docs pull request #177
Opened 2023-06-12 14:50 UTC by melonora

# Description
Documentation for the new polygon tool in the label layer

## Type of change
- [x] Adds new content page(s)

# References
[#5806](https://github.com/napari/napari/pull/5806)

2023-06-12 15:24 UTC, psobolewskiPhD commented
@melonora 
FYI, we have a `depends on` checker action, so you can add:
`Depends on https://github.com/napari/napari/pull/5806`
See: https://github.com/napari/docs/pull/124

And this way it will not be accidentally merged before the actual feature is in.
We probably need to consider milestones too, because a 0.5.0 feature shouldn't be documented in `stable` till 0.5.0

2023-06-12 15:41 UTC, psobolewskiPhD requested changes
Thanks for this!
Made a few tiny suggestions—only the first is important, because something is missing or duplicated.

2023-06-12 15:41 UTC, psobolewskiPhD commented on docs/howtos/layers/labels.md
> +the mouse. A vertex to be added will track your mouse cursor and a line with the
```suggestion
polygon in the layer control panel or by pressing `3`. Once activated, left-click 
anywhere on the canvas to start drawing the polygon. A vertex to be added will track your mouse cursor and a line with the 
```

2023-06-12 15:41 UTC, psobolewskiPhD commented on docs/howtos/layers/labels.md
> +adjusts the label layer in one plane, with the exception when viewing the image data as RGB.
```suggestion
Note: if you use the `polygon` tool for adding or editing segmentations of 3D image data, you can only 
adjust labels in one plane, with the exception when viewing the image data as RGB. 
```

2023-06-13 06:09 UTC, psobolewskiPhD approved these changes

2023-06-13 12:15 UTC, ksofiyuk commented
@melonora Thank you for preparing the docs for the polygon tool. I've looked through it and I think that it would be better to change the document structure a little bit:

- Put the brush tool and the polygon tool in the same section called "Painting in the labels layer" as subsections as the polygon tool is just another way of painting in the labels layer. Both tools are different ways of painting, so I think they should be in one place.
- Replace paragraphs describing the polygon actions and their shortcuts with a corresponding bullet list. I find it not very convenient to navigate through paragraphs of texts if you just need to have a cursory view of the tool and its shortcuts.

> It combines functionality of the paintbrush and fill bucket tool. 

I think this sentence is a bit confusing as the polygon tool does not actually combine them. In that sense, the brush is a combination of the circle and the fill bucket tool, which does not make sense to me :smile:. I don't think that there should be any links between the fill bucket tool and the polygon tool.

2023-06-22 09:42 UTC, melonora commented
> @melonora Thank you for preparing the docs for the polygon tool. I've looked through it and I think that it would be better to change the document structure a little bit:
> 
>     * Put the brush tool and the polygon tool in the same section called "Painting in the labels layer" as subsections as the polygon tool is just another way of painting in the labels layer. Both tools are different ways of painting, so I think they should be in one place.
> 
>     * Replace paragraphs describing the polygon actions and their shortcuts with a corresponding bullet list. I find it not very convenient to navigate through paragraphs of texts if you just need to have a cursory view of the tool and its shortcuts.
> 
> 
> > It combines functionality of the paintbrush and fill bucket tool.
> 
> I think this sentence is a bit confusing as the polygon tool does not actually combine them. In that sense, the brush is a combination of the circle and the fill bucket tool, which does not make sense to me 😄. I don't think that there should be any links between the fill bucket tool and the polygon tool.

I changed it to bullet point format to provide a clearer overview. As for putting both in a section `Painting labels in layer`, I did not opt for that as the same could also be said for the fill bucket. Regarding the combined functionality, I now explicitly state that it does so by allowing for readily drawing enclosed instance segmentations

2023-07-06 13:30 UTC, merged