add link to video from EMBO workshop
napari/docs pull request #273
Opened 2023-11-19 13:41 UTC by haesleinhuepf

Hi all,

I'm proposing another link for the list of workshops. 

Btw. I'm wondering is this the right page that is rendered here?
https://napari.org/stable/further-resources/napari-workshops.html

That one seems out of sync.

Thanks!
Best,
Robert

2023-11-19 14:56 UTC, Czaki commented
This is current page: https://napari.org/dev/further-resources/napari-workshops.html

We have a plan to work on updating part of the webpage without releasing napari. but it is not done yet.

2023-11-19 14:56 UTC, Czaki approved these changes

2023-11-19 17:48 UTC, psobolewskiPhD requested changes
I think it would be nice to link to the page of the course/embl -- did I get the link right @haesleinhuepf ?

2023-11-19 17:48 UTC, psobolewskiPhD commented on docs/further-resources/napari-workshops.md
> +  * [Bioimage Analysis with Python and Napari (video lecture)](https://www.youtube.com/watch?v=QDS5t7oZH-c) at the EMBO Practical Course for Advanced Methods in Bioimage Analysis
```suggestion
  * [Bioimage Analysis with Python and Napari (video lecture)](https://www.youtube.com/watch?v=QDS5t7oZH-c) at the [EMBO Practical Course for Advanced Methods in Bioimage Analysis](https://www.embl.org/about/info/course-and-conference-office/events/bia23-01/) 
```
I think that's the proper link for anyone that wants a bit more background about the video.

2023-11-20 21:11 UTC, haesleinhuepf commented
> I think it would be nice to link to the page of the course/embl -- did I get the link right @haesleinhuepf ?

yes, great hint @psobolewskiPhD !

2023-11-20 22:31 UTC, psobolewskiPhD commented on docs/further-resources/napari-workshops.md
> +  * [plugin design](https://chanzuckerberg.github.io/napari-plugin-accel-workshops/workshops/design23.html) and [software development workshop](https://chanzuckerberg.github.io/napari-plugin-accel-wo
```suggestion
  * [Plugin design](https://chanzuckerberg.github.io/napari-plugin-accel-workshops/workshops/design23.html) and [software development workshop](https://chanzuckerberg.github.io/napari-plugin-accel-workshops/workshops/softwaredev.html) for [napari plugin grantees](https://chanzuckerberg.com/rfa/napari-plugin-grants/).
```

2023-11-20 22:32 UTC, psobolewskiPhD commented on docs/further-resources/napari-workshops.md
> +  * [Bioimage Analysis with Python and Napari (video lecture)](https://www.youtube.com/watch?v=QDS5t7oZH-c) at the [EMBO Practical Course for Advanced Methods in Bioimage Analysis](https://www.embl.o
```suggestion
  * [Bioimage Analysis with Python and Napari (video lecture)](https://www.youtube.com/watch?v=QDS5t7oZH-c) at the [EMBO Practical Course for Advanced Methods in Bioimage Analysis](https://www.embl.org/about/info/course-and-conference-office/events/bia23-01/)  
  
 
```

2023-11-20 22:33 UTC, psobolewskiPhD approved these changes
Made a tiny tweak: capitol P and some an empty line

2023-11-20 22:50 UTC, psobolewskiPhD commented
Hmm...something is up with the CircleCI previews...
I'm getting
```
{"message":"not found"}
```
Here's what the downloaded artifact looks like:
<img width="779" alt="image" src="https://github.com/napari/docs/assets/76622105/f68e7dd1-98e8-4e45-81e7-62ffa3ae9e3f">

2023-11-21 21:24 UTC, psobolewskiPhD commented
> Hmm...something is up with the CircleCI previews...

This has been resolved by https://github.com/napari/docs/pull/278

2023-11-22 01:53 UTC, merged