Unify docs workflows
napari/docs pull request #348
Opened 2024-02-01 11:16 UTC by Czaki

# Description

This PR:

Unify build workflows from two to one. 

Remove .doctree directory (save 40MB)

2024-02-01 11:18 UTC, melissawm approved these changes
Looks good, thank you!

2024-02-14 21:33 UTC, psobolewskiPhD commented
Should delete the .doctrees from the uploaded artifact IMO. They aren't needed for anything related to the html as far as I understand.

2024-02-15 11:03 UTC, Czaki commented
I do not know. Maybe they are usefull for some debug. I'm not such familiar with sphinx

2024-02-15 16:34 UTC, psobolewskiPhD commented
here's the info:
> Since Sphinx has to read and parse all source files before it can write an output file, the parsed source files are cached as “doctree pickles”. Normally, these files are put in a directory called .doctrees under the build directory; with this option you can select a different cache directory (the doctrees can be shared between all builders).

https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-d

They aren't needed for the website. I guess instead of delete, we could change the dir to not put them in the folder used for the artifact?

2024-02-20 01:12 UTC, jni approved these changes
maybe rename the workflow to build_and_deploy.yml?

2024-02-20 01:13 UTC, jni commented
And I agree with @psobolewskiPhD that maybe we should just configure the .doctree dir to be in /tmp or something. And/or make a PR to sphinx to not put it in the build in the first place. 😂

2024-02-27 11:52 UTC, jni commented
@Czaki 

> maybe rename the workflow to build_and_deploy.yml?

> maybe we should just configure the .doctree dir to be in /tmp or something.

Do you want to implement either or both of these, or none?

2024-02-28 21:28 UTC, psobolewskiPhD commented
I did some more digging around the sphinx docs, readthedocs docs, etc.
The defaults these days is to use `-M` instead of `-b` which puts the doctrees separate from the html. See:
https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-M
(html is the default builder)
So the you'd get:
```
docs/_build/html
docs/_build/doctrees
```

See for example:
https://www.sphinx-doc.org/en/master/tutorial/deploying.html#id5
where only the html is deployed to Github Pages.

2024-02-28 21:49 UTC, psobolewskiPhD commented
I second the motion to change the name to build_and_deploy
I made a PR suggesting what I think the the proper way to handle the doctrees question.

2024-02-28 21:49 UTC, psobolewskiPhD requested changes
I second the motion to rename the new workflow to `build_and_deploy.yml`

2024-02-29 06:05 UTC, jni commented
> I made a PR suggesting what I think the the proper way to handle the doctrees question.

Fantastic detective work @psobolewskiPhD! 🕵️ 🤓

2024-03-01 01:35 UTC, psobolewskiPhD commented on .github/workflows/build_and_deploy.yml
> +            echo "branch_name=${{ github.ref/refs\/tags\// }}" >> $GITHUB_ENV
```suggestion
            echo "branch_name=${{ github.ref\/refs\/tags\// }}" >> $GITHUB_ENV 
```
I think this fixes the error:
https://github.com/napari/docs/actions/runs/8103613500

2024-03-01 01:37 UTC, psobolewskiPhD commented on .circleci/config.yml
> +          path: docs/docs/_build/html
```suggestion
          path: docs/docs/_build/html/
```

2024-03-01 01:37 UTC, psobolewskiPhD commented on .circleci/config.yml
> +            - docs/docs/_build/html
```suggestion
            - docs/docs/_build/html/
```

2024-03-01 02:00 UTC, psobolewskiPhD commented on .github/workflows/build_and_deploy.yml
> +            echo "branch_name=${{ github.ref\/refs\/tags\// }}" >> $GITHUB_ENV
```suggestion
            echo "branch_name=${{ github.ref_name }}" >> $GITHUB_ENV 
```

2024-03-01 02:08 UTC, psobolewskiPhD commented
Per docs here https://github.com/larsoner/circleci-artifacts-redirector-action
The circleCI redirector is expected to not work properly until this is merged.

2024-03-01 02:11 UTC, psobolewskiPhD approved these changes
I think everything is good now.
@Czaki Can you sanity check the tags bit?

2024-03-02 14:32 UTC, Czaki commented
> I think everything is good now.
> @Czaki Can you sanity check the tags bit?

What tags?

2024-03-02 14:55 UTC, psobolewskiPhD commented
This fix:
https://github.com/napari/docs/pull/348/commits/928551d5144ba182a629181ea96c1b4c9a94d185
to this error:
https://github.com/napari/docs/actions/runs/8103613500

2024-03-02 15:41 UTC, Czaki commented
> This fix: [928551d](https://github.com/napari/docs/commit/928551d5144ba182a629181ea96c1b4c9a94d185) to this error: [napari/docs/actions/runs/8103613500](https://github.com/napari/docs/actions/runs/8103613500)

You suggest change in getting value from tags and point skipped action (caused by file rename I think).

2024-03-02 15:54 UTC, psobolewskiPhD commented
Sorry if I wasn't being clear.
This action was failing with:
```
The workflow is not valid. .github/workflows/build_and_deploy.yml (Line: 92, Col: 14): Unexpected symbol: 'ref/refs\/tags\//'. Located at position 8 within expression: github.ref/refs\/tags\//
```
Here's that code section before my fix:
https://github.com/napari/docs/blob/8b695ca58ebda1d186f8feba9c5bea5fd47d304a/.github/workflows/build_and_deploy.yml#L92-L97

As far As I can tell, in `github.ref/refs\/tags\//` `/refs\/tags\//` is trying to get the name of the tag, so my fix is to use it directly, based on https://docs.github.com/en/actions/learn-github-actions/contexts

2024-03-02 15:55 UTC, psobolewskiPhD commented
Because this is for deployment, it's not easy to check, so hence asking you to sanity check before we merge this and find out docs don't deploy right!

2024-03-21 20:21 UTC, melissawm commented
It looks like this is good to go, pending @psobolewskiPhD 's  comment above? If so, I just want to point out that if the deploy fails it's an easy fix and doesn't break the website (it will only not show the latest version until we fix it). So I'd say this is pretty safe.

2024-03-24 19:45 UTC, psobolewskiPhD commented
I pushed the changes to the workflow from the video conversion PR.

2024-03-25 19:59 UTC, melissawm commented
I am marking this as ready as I believe it's done - @Czaki last chance to take a look 😄

2024-03-25 21:27 UTC, Czaki commented
I think it is ready. Still do not know what with deploy trigger.

2024-03-27 19:35 UTC, merged