[WIP] Add basic layer modes description
napari/docs pull request #420
Opened 2024-05-08 18:43 UTC by dalthviz

# References and relevant issues

Depends on https://github.com/napari/napari/pull/6794

# Description

Adds new content related with layers transform mode and base possible values (`pan_zoom` and `transform`)

2024-05-20 20:05 UTC, melissawm reviewed
Did an initial pass, only a couple comments. Thanks @dalthviz !

2024-05-20 20:05 UTC, melissawm commented on docs/guides/layers.md
> +with the layer from the viewer. These modes are accesible via the layer controls
```suggestion
with the layer from the viewer. These modes are accessible via the layer controls
```

2024-05-20 20:05 UTC, melissawm commented on docs/guides/layers.md
> +available. Currently, there are two base modes:
I think this is confusing - the sentence makes it seem like for any layer type, pressing 1 would activate the pan/zoom or transform modes and that's not the case. Maybe we don't need to mention a number here and just say

```suggestion
widget top buttons and via keyboard shortcuts (these shortcuts will vary depending on the layer type). Currently, there are two base modes:
```

2024-05-20 20:05 UTC, melissawm commented on docs/howtos/layers/shapes.md
> +  confirm the reset).
The `6` and `7` keyboard shortcuts are also valid here.

2024-05-21 15:26 UTC, dalthviz commented on docs/howtos/layers/shapes.md
> +  confirm the reset).
Hi @melissawm thanks for the review! You mean changing this to be something like:

```
 Use this tool to rotate, scale, or translate the layer. To activate the tool, you can
 press `7`. To reset the transformation, you can Option/Alt-click the transform
 button (a confirmation dialog will open to confirm the reset).
```

?

2024-05-22 13:49 UTC, melissawm commented on docs/howtos/layers/shapes.md
> +  confirm the reset).
Yes - and add the information about the keyboard shortcut to the pan/zoom tool as well if you can. Thanks!

2024-05-23 17:59 UTC, melissawm approved these changes
Looks good to me, thanks @dalthviz !

2024-06-06 02:30 UTC, psobolewskiPhD commented on docs/guides/layers.md
> +the default mode selected.
```suggestion
the default mode selected. Note: zooming with the mouse-wheel should essentially always work!
```

2024-06-06 02:32 UTC, psobolewskiPhD commented on docs/guides/layers.md
> +![image: Pan/zoom](../images/pan-zoom-tool.png)
Could we use the icon that's in 0.4.19, the pan icon?
https://github.com/napari/napari/blob/main/napari/resources/icons/pan_arrows.svg
It's confusing that the mode is called `pan_zoom`, but zoom essentially always works with the mouse wheel, so it's really `pan` that's unique to the mode.

2024-06-06 02:33 UTC, psobolewskiPhD commented on docs/guides/layers.md
> +graphically. To reset the transformation, you can Option/Alt-click the transform
```suggestion
graphically. Note: at present this only works in 2D viewer display mode.
To reset the transformation, you can Option/Alt-click the transform
```

2024-06-06 02:34 UTC, psobolewskiPhD commented on docs/howtos/layers/image.md
> +  rotate, scale, or translate the layer. To reset the transformation,
```suggestion
  rotate, scale, or translate the layer. Note: at present this feature is limited to 2D viewer display mode.
  To reset the transformation,
```

2024-06-06 02:34 UTC, psobolewskiPhD commented on docs/howtos/layers/labels.md
> +`layer controls` panel. It enables you to rotate, scale, or translate the layer.
```suggestion
`layer controls` panel. It enables you to rotate, scale, or translate the layer.
Note: at present this feature is limited to 2D viewer display mode.
```

2024-06-06 02:35 UTC, psobolewskiPhD commented on docs/howtos/layers/points.md
> +  Use this tool to rotate, scale, or translate the layer. To reset the transformation,
```suggestion
  Use this tool to rotate, scale, or translate the layer. 
  Note: at present this feature is limited to 2D viewer display mode. To reset the transformation,
```

2024-06-06 02:37 UTC, psobolewskiPhD commented on docs/howtos/layers/shapes.md
> +  Use this tool to rotate, scale, or translate the layer. To activate the tool,
```suggestion
  Use this tool to rotate, scale, or translate the layer. Note: at present this feature is limited to 2D viewer display mode. To activate the tool,
```

2024-06-06 02:37 UTC, psobolewskiPhD commented on docs/howtos/layers/shapes.md
> +  is disabled when using the adding and editing tools. To activate the tool,
```suggestion
  Use this tool to pan around the layer or zoom in. Pan functionality
  is disabled when using the adding and editing tools; however, zoom using the mouse-wheel will typically continue to work. To activate the tool,
```

2024-06-06 02:37 UTC, psobolewskiPhD commented on docs/howtos/layers/surface.md
> +    rotate, scale, or translate the layer. To reset the transformation, you can
```suggestion
    rotate, scale, or translate the layer. Note: at present this feature is limited to 2D viewer display mode. To reset the transformation, you can
```

2024-06-06 02:38 UTC, psobolewskiPhD commented on docs/howtos/layers/tracks.md
> +    rotate, scale, or translate the layer. To reset the transformation, you can
```suggestion
    rotate, scale, or translate the layer. Note: at present this feature is limited to 2D viewer display mode. To reset the transformation, you can
```

2024-06-06 02:38 UTC, psobolewskiPhD commented on docs/howtos/layers/vectors.md
> +    rotate, scale, or translate the layer. To reset the transformation, you can
```suggestion
    rotate, scale, or translate the layer. Note: at present this feature is limited to 2D viewer display mode. To reset the transformation, you can
```

2024-06-06 02:40 UTC, psobolewskiPhD requested changes
Thanks @dalthviz 
I made a few suggestions to clarify that translate only works in 2D viewer mode.
I'm still not sure we should be even more explicit that it *works* on 3D **layers** but only in 2D viewer mode?
Also I tried to clarify the pan/zoom bit -- I'd prefer we use the 0.4.19 arrows/pan icon.

2024-06-07 15:32 UTC, dalthviz commented
> I'm still not sure we should be even more explicit that it works on 3D layers but only in 2D viewer mode?

I would say the added note should be enough but maybe asking for feedback to others could be worthy

2024-06-07 18:44 UTC, psobolewskiPhD approved these changes
Thanks @dalthviz !
Looks good to me.

2024-07-11 04:12 UTC, merged