Update finding and installing plugin docs
napari/docs pull request #541
Opened 2024-12-17 20:19 UTC by melissawm

# References and relevant issues
Closes #122

# Description
- Update screenshot and text to reflect current state of napari plugin manager (also adds links to their docs)

2024-12-19 16:49 UTC, melissawm commented
@TimMonko would you mind reviewing these changes? I'd be more than happy to address any suggestion you may have for improvements. Cheers!

2024-12-19 18:28 UTC, TimMonko requested changes
Thanks for pinging me to leave a review. This is the first time I've reviewed a PR, so it took me a bit to figure anything out. Let me know if there is some review-specific etiquette or something that I've missed

2024-12-19 18:28 UTC, TimMonko commented on docs/plugins/start_using_plugins/finding_and_installing_plugins.md
> +- **napari hub:** The [napari hub](https://napari-hub.org) uses this data, together with additional
'This data' is ambiguous. I'm not sure how necessary it is. Maybe just something like' The napari-hub uses plugin-provided metadata to produce a more user-friendly way to find napari plugins.

2024-12-19 18:28 UTC, TimMonko commented on docs/plugins/start_using_plugins/finding_and_installing_plugins.md
> +directly from within napari, using the [napari plugin manager](https://napari.org/napari-plugin-manager/).
Perhaps it should be stated that npm is only installed with `pip install napari[all]`, `conda install napari`, and the bundled app?

2024-12-19 18:28 UTC, TimMonko commented on docs/plugins/start_using_plugins/finding_and_installing_plugins.md
> +   say either "install with 'pip' by name/url, or drop file...", or "install with 'pip' by name/url, or drop file..."
I assume this is meant to say 'conda' or something for one of them? Right now both say 'pip'. (my npm is currently not connecting in any install, no idea why, so I can't check)

2024-12-19 18:28 UTC, TimMonko commented on docs/plugins/start_using_plugins/finding_and_installing_plugins.md
> +3. Advanced installation: after you have searched for the plugin you with to install, clicking on "Installation Info"
```suggestion
3. Advanced installation: after you have searched for the plugin you wish to install, clicking on "Installation Info"
```

2024-12-19 18:28 UTC, TimMonko commented on docs/plugins/start_using_plugins/finding_and_installing_plugins.md
>  in the `Plugins > Install/Uninstall Plugins` menu.
```suggestion

```

2024-12-19 18:28 UTC, TimMonko commented on docs/plugins/start_using_plugins/finding_and_installing_plugins.md
>  in the `Plugins > Install/Uninstall Plugins` menu.
Redundant with below section, but especially with `testing_and_publish/deploy.md`

2024-12-19 18:28 UTC, TimMonko commented on docs/plugins/virtual_environment_docs/2-deploying-your-plugin.md
```suggestion

Note that in order to deploy to `conda-forge` *all* build and run requirements (i.e. dependencies) *must* be available on `conda-forge`. 

```

2024-12-19 18:28 UTC, TimMonko commented on docs/plugins/virtual_environment_docs/2-deploying-your-plugin.md
>  This is **far** easier if you already have an `sdist` published to PyPI.
```suggestion
This is **far** easier if you already have an `sdist` published to PyPI.

Updating your package on conda-forge: By default, when a new release is detected on PyPI, conda-forge bots will automatically make a pull requests to your `conda-forge/package-name-feedstock` and you must address any changes and approve the pull request.
```

2024-12-19 18:28 UTC, TimMonko commented on docs/plugins/virtual_environment_docs/2-deploying-your-plugin.md
>  This is **far** easier if you already have an `sdist` published to PyPI.
Style this better than I have, but I think this is really important to add

2024-12-19 18:28 UTC, TimMonko commented on docs/plugins/start_using_plugins/finding_and_installing_plugins.md
This is great. What comes to mind as missing is mention of how to upgrade plugins. I think, by default, a user has to uninstall and then reinstall the version they want. Is that correct? Is this the recommended way?

2024-12-19 18:29 UTC, melissawm commented on docs/plugins/start_using_plugins/finding_and_installing_plugins.md
> +   say either "install with 'pip' by name/url, or drop file...", or "install with 'pip' by name/url, or drop file..."
oops yes, wrong copy/paste!

2024-12-20 00:00 UTC, psobolewskiPhD commented on docs/plugins/start_using_plugins/finding_and_installing_plugins.md
> +directly from within napari, using the [napari plugin manager](https://napari.org/napari-plugin-manager/).
Oh this is a good point! The plugin manager has been devolved, so it's not in napari/napari anymore.

2024-12-20 00:23 UTC, psobolewskiPhD commented on docs/plugins/start_using_plugins/finding_and_installing_plugins.md
the new plugin manager should update plugins too.

2024-12-20 01:15 UTC, TimMonko commented on docs/plugins/start_using_plugins/finding_and_installing_plugins.md
Automagically? I remember there used to be an 'upgrade' button or something, but on main that doesn't seems to be the case -- just uninstall is available (the plugin here has v0.9.7 available through npm, I intentionally used npm to download v0.9.5):
![image](https://github.com/user-attachments/assets/61267920-12f3-4657-8868-d2e5e7f1a865)

```
napari: 0.5.6.dev10+g224f8e9c
Platform: Windows-11-10.0.22631-SP0
Python: 3.12.8 | packaged by conda-forge | (main, Dec 5 2024, 14:06:27) [MSC v.1942 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.11
NumPy: 1.26.4
SciPy: 1.14.1
Dask: 2024.12.1
VisPy: 0.14.3
magicgui: 0.10.0
superqt: 0.7.0
in-n-out: 0.2.1
app-model: 0.3.1
psygnal: 0.11.1
npe2: 0.7.7
pydantic: 2.10.4

OpenGL:
- GL version: 4.6.0 NVIDIA 551.78
- MAX_TEXTURE_SIZE: 32768
- GL_MAX_3D_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 2.0
- screen 2: resolution 1440x2560, scale 1.0

Optional:
- numba: 0.60.0
- triangle: 20230923
- napari-plugin-manager: 0.1.3

Settings path:
- C:\Users\timmo\AppData\Local\napari\napari-testing_e9e6cb9e948feb28aa4661b58255680aebaae620\settings.yaml
```

2024-12-20 01:15 UTC, TimMonko commented
Another thing that I've just come across is this little bugger that could go into the documentation (or get a PR to change the behavior):

Right now, when you install a plugin through npm, the little loading animation will keep going and going AND if you've clicked off napari, then you won't know that isn't what the issue is. Instead its... the little npe2 restart popup causing npm to hang as if it was still installing
![image](https://github.com/user-attachments/assets/9754128d-cbba-4356-b7df-5780329f5f95)

Once this little popup is closed, the loading animation stops and everything looks normal. Even to me as a user with experience, I often forget that it is actually done installing the plugin when I'm helping users work through npm (because the animation continues)

2024-12-21 04:21 UTC, psobolewskiPhD commented
@TimMonko that sounds like a bug -- can you open an issue here https://github.com/napari/napari-plugin-manager

2024-12-21 04:28 UTC, psobolewskiPhD commented on docs/plugins/start_using_plugins/finding_and_installing_plugins.md
Um it should work?
https://napari.org/napari-plugin-manager/index.html#updating-a-plugin
Maybe there's been a regression somewhere or it's another conda vs pip difference?

2025-01-17 14:01 UTC, psobolewskiPhD commented
I'll try to be more concrete, but putting this here so I don't forget before rushing off to a meeting:
we should document the differences in behavior of the plugin manager between bundle and normal python app.
I made an issue in the manager repo, but see also: https://github.com/napari/napari/issues/7534#issuecomment-2598376755

2025-02-13 20:22 UTC, willingc approved these changes
I've gone through and made suggestions for all open items. If they are applied this PR should be in a mergeable state. Thanks @psobolewskiPhD @TimMonko for the reviews and @melissawm for the pr.

2025-02-13 20:22 UTC, willingc commented on docs/plugins/start_using_plugins/finding_and_installing_plugins.md
> +  metadata, to produce a more user-friendly way to find napari plugins.
```suggestion
  metadata, to produce a user-friendly way to find napari plugins.
```

2025-02-13 20:22 UTC, willingc commented on docs/plugins/start_using_plugins/finding_and_installing_plugins.md
> +- **napari hub:** The [napari hub](https://napari-hub.org) uses this data, together with additional
```suggestion
- **napari hub:** The [napari hub](https://napari-hub.org) uses package data, together with additional
```

2025-02-13 20:22 UTC, willingc commented on docs/plugins/start_using_plugins/finding_and_installing_plugins.md
> +directly from within napari, using the [napari plugin manager](https://napari.org/napari-plugin-manager/).
```suggestion
directly from within napari, when the user has installed the [napari plugin manager](https://napari.org/napari-plugin-manager/).
```

2025-02-13 20:22 UTC, willingc commented on docs/plugins/start_using_plugins/finding_and_installing_plugins.md
> +To install a new plugin, click the "Plugins" menu and select "Install/Uninstall Plugins...".
```suggestion
After the napari plugin manager is available, install a plugin by clicking the "Plugins" menu and selecting "Install/Uninstall Plugins...".
```

2025-02-13 20:22 UTC, willingc commented on docs/plugins/start_using_plugins/finding_and_installing_plugins.md
> +   say either "install with 'pip' by name/url, or drop file...", or "install with 'pip' by name/url, or drop file..."
```suggestion
   say either "install with 'pip' by name/url, or drop file...", or "install with 'conda' by name/url, or drop file..."
```

2025-02-13 20:22 UTC, willingc commented on docs/plugins/virtual_environment_docs/2-deploying-your-plugin.md
> +PyPI and conda are two options for how you distribute your package and allow your users to more easily find and install it.  Try to deploy to both! But for now, try to at least use PyPI. You can alwa
```suggestion
PyPI and conda are two options for how you distribute your package and allow your users to more easily find and install it.  Ideally, try to deploy to both. But for now, try to at least use PyPI. You can always also provide your users with manual installation instructions (e.g. if you want them to use `conda` or have specific dependencies).
```

2025-02-13 20:22 UTC, willingc commented on docs/plugins/virtual_environment_docs/2-deploying-your-plugin.md
I like Tim's note, I would clarify his wording a bit more.
```
To deploy a plugin to `conda-forge`, the plugin's build and run requirements **must** be available on `conda-forge` so the plugin and its dependencies may be installed.

2025-02-13 20:22 UTC, willingc commented on docs/plugins/virtual_environment_docs/2-deploying-your-plugin.md
>  This is **far** easier if you already have an `sdist` published to PyPI.
```
 your `conda-forge/package-name-feedstock`, and the plugin maintainer must review, make changes, if needed,  and approve the pull request.
```

2025-02-13 20:35 UTC, melissawm commented on docs/plugins/virtual_environment_docs/2-deploying-your-plugin.md
>  This is **far** easier if you already have an `sdist` published to PyPI.
```suggestion
This is **far** easier if you already have an `sdist` published to PyPI.

Updating your package on conda-forge: By default, when a new release is detected on PyPI, conda-forge bots will automatically make a pull requests to your `conda-forge/package-name-feedstock`, and the plugin maintainer must review, make changes, if needed,  and approve the pull request.
```

2025-02-13 20:36 UTC, melissawm commented on docs/plugins/virtual_environment_docs/2-deploying-your-plugin.md
```suggestion
To deploy a plugin to `conda-forge`, the plugin's build and run requirements **must** be available on `conda-forge` so the plugin and its dependencies may be installed.
```

2025-02-13 21:23 UTC, psobolewskiPhD approved these changes
Looks great! Sorry I dropped the ball on this one!
Mega thanks to @willingc for picking it up!
❤️

2025-02-13 21:51 UTC, TimMonko approved these changes
Looks great! 
Really like the changes especially to some of the language I suggested -- much clearer @willingc @melissawm

2025-02-13 21:51 UTC, TimMonko commented on docs/plugins/virtual_environment_docs/2-deploying-your-plugin.md
> +Updating your package on conda-forge: By default, when a new release is detected on PyPI, conda-forge bots will automatically make a pull requests to your `conda-forge/package-name-feedstock`, and th
Can we have this in an admonition? It's not quite obvious enough to me.  

At least bolding it would be nice. 
```suggestion
**Updating your package on conda-forge:** By default, when a new release is detected on PyPI, conda-forge bots will automatically make a pull requests to your `conda-forge/package-name-feedstock`, and the plugin maintainer must review, make changes, if needed,  and approve the pull request.
```

2025-02-13 21:57 UTC, melissawm commented on docs/plugins/virtual_environment_docs/2-deploying-your-plugin.md
> +Updating your package on conda-forge: By default, when a new release is detected on PyPI, conda-forge bots will automatically make a pull requests to your `conda-forge/package-name-feedstock`, and th
```suggestion
```{admonition} Updating your package on conda-forge
:class: important

By default, when a new release is detected on PyPI, conda-forge bots will automatically make a pull requests to your `conda-forge/package-name-feedstock`, and the plugin maintainer must review, make changes, if needed,  and approve the pull request.
```
```

2025-02-13 21:57 UTC, melissawm commented on docs/plugins/virtual_environment_docs/2-deploying-your-plugin.md
> +Updating your package on conda-forge: By default, when a new release is detected on PyPI, conda-forge bots will automatically make a pull requests to your `conda-forge/package-name-feedstock`, and th
Let's see if the admonition turns out nice.

2025-02-13 22:22 UTC, TimMonko commented on docs/plugins/virtual_environment_docs/2-deploying-your-plugin.md
> +By default, when a new release is detected on PyPI, conda-forge bots will automatically make a pull requests to your `conda-forge/package-name-feedstock`, and the plugin maintainer must review, make
````suggestion
By default, when a new release is detected on PyPI, conda-forge bots will automatically make a pull requests to your `conda-forge/package-name-feedstock`, and the plugin maintainer must review, make changes, if needed,  and approve the pull request.
```
````

2025-02-13 22:23 UTC, TimMonko commented on docs/plugins/virtual_environment_docs/2-deploying-your-plugin.md
> +By default, when a new release is detected on PyPI, conda-forge bots will automatically make a pull requests to your `conda-forge/package-name-feedstock`, and the plugin maintainer must review, make
Needs the closing ticks, but I do like how it looks on the docs!

2025-02-13 22:28 UTC, melissawm commented on docs/plugins/virtual_environment_docs/2-deploying-your-plugin.md
> +By default, when a new release is detected on PyPI, conda-forge bots will automatically make a pull requests to your `conda-forge/package-name-feedstock`, and the plugin maintainer must review, make
Github mangled the backticks on the suggestion 🙃

2025-02-13 23:46 UTC, melissawm commented
I think this is ready - thank you so much all!

2025-02-14 00:45 UTC, merged