Add docs on advanced contrast limits widget
napari/docs pull request #542
Opened 2024-12-18 20:38 UTC by melissawm

# References and relevant issues
Closes #535

# Description
Borrows some word from the discussion on #533, and adds a small video to showcase and document the advanced contrast limits widget.

2024-12-19 00:25 UTC, psobolewskiPhD requested changes
I made some suggestions to elaborate a few of the details a bit more.

2024-12-19 00:25 UTC, psobolewskiPhD commented on docs/howtos/layers/image.md
> +such that any value under the smaller contrast limit will appear as black. On
```suggestion
meaning that in most cases any value under the smaller contrast limit will appear as black. On
```
I think it's better to generalize this? We have LUT where 0 isn't mapped to black.

2024-12-19 00:25 UTC, psobolewskiPhD commented on docs/howtos/layers/image.md
> +of image data larger than this value will appear as white.
```suggestion
data that will get mapped to the color defined by 1 in the colormap. For example, for an image using the `gray` colormap, all values larger than this value will appear as white.
```
Same as above, let's generalize?

2024-12-19 00:25 UTC, psobolewskiPhD commented on docs/howtos/layers/image.md
>  As of right now, adjusting the contrast limits has no effect for `rgb` data.
```suggestion
For RGB images, adjusting the contrast limits adjusts the black point and white point of the image.
```

2024-12-19 00:25 UTC, psobolewskiPhD commented on docs/howtos/layers/image.md
> +
```suggestion

For more precise control, you can right-click on the contrast limits slider to show a version of the slider with numerical values. Importantly, all four displayed values can be edited by clicking on them. Editing the numbers above the circular slider handles allows you to precisely specify values for the two contrast limits. Press the {kbd}`Enter` or {kbd}`Return` to confirm the new value.
Meanwhile, the numbers at the two ends of the horizontal rule let you change the *range* of the contrast limits slider (programmatically accessed using the `contrast_limits_range` property). Clicking the `full range` button will reset the contrast limits slider range back to the full range of the data type (e.g. 0 and 255 for `uint8`). Finally, clicking the `reset` button will reset *both* the contrast limits *and* the contrast limits range to the full range of the data type.
```

2024-12-19 00:25 UTC, psobolewskiPhD commented on docs/howtos/layers/image.md
> +limits to do manual adjustment, including directly editing the numbers shown or
We can leave this, but looking at the code and testing a bit with:
```
data = np.array([[10, 15], [20 ,25]], dtype=np.uint8)
```
I *think* that `once` and `reset` do exactly the same thing.
I was expecting `once` to use the data range, but it uses dtype range.

`once` and `continuous` should get tooltips -- i'll add that to an existing issue with contrast limits in napari/napari

2024-12-19 00:25 UTC, psobolewskiPhD commented on docs/howtos/layers/image.md
> +extent of the `contrast limits:` range slider will be set to those values.
````suggestion
```{important}
If you pass `contrast_limits` as a keyword argument to a layer, then the full
extent of the `contrast limits:` range slider will also be set to those values!
```
````
This is really insidious, lets make it an admonition.

2024-12-19 00:46 UTC, psobolewskiPhD commented on docs/howtos/layers/image.md
> +limits to do manual adjustment, including directly editing the numbers shown or
Ok , nvm, confusingly, once and reset do the same thing for the case of unit8 but not the others, where once will only reset contrast limits and not their range.

2024-12-19 23:56 UTC, psobolewskiPhD commented on docs/howtos/layers/image.md
> +Meanwhile, the numbers at the two ends of the horizontal rule let you change the *range* of the contrast limits slider (programmatically accessed using the `contrast_limits_range` property). Clicking
```suggestion
Meanwhile, the numbers at the two ends of the horizontal rule let you change the *range* of the contrast limits slider (programmatically accessed using the `contrast_limits_range` property). Clicking the `full range` button will reset the contrast limits slider range back to the full range of the data type (e.g. 0 and 255 for `uint8`). Finally, clicking the `reset` button will reset *both* the contrast limits *and* the contrast limits range to the full range for uint8 images (0, 255), and to the minimum and maximum of the *data* for other data types.
```
Ooof this is very confusing, but correct.
uint8 is a special case where full range is always used.
data range is used for everything else -- and there is no easy way to reset to full range!

2024-12-20 21:45 UTC, psobolewskiPhD approved these changes
thanks @melissawm !!

2024-12-21 19:01 UTC, TimMonko reviewed
Overall, these are great changes! The animation is super useful and I think the explanation of the advanced contrast limits works great. Two more things I could see being useful to add (could be in a separate PR):

1. Explanation of once/continuous buttons. Continuous in particular has a lot of use that is not immediately obvious.
2. Explanation of gamma, since that is the last main way to change the visualization of the cmaps.

2024-12-21 19:01 UTC, TimMonko commented on docs/_static/images/contrast_limits.webm
Fabulous animation. I'm just checking that you intend for it to be slowed down. I think it being slowed down helps the user see the actions being made, but I also wouldn't want people to think napari is laggy. I am in favour of keeping it the way it currently is.

2024-12-21 19:01 UTC, TimMonko commented on docs/howtos/layers/image.md
> +data that will get mapped to the color defined by 1 in the colormap. For example, for an image using the `gray` colormap, all values larger than this value will appear as white.
```suggestion
data that will get mapped to the color defined by 1 in the colormap; for an image using the `gray` colormap, all values larger than this value will appear as white. Note that the values set in the contrast limits do not change the underlying values of the image, only the visualization of the colormap. 
```

2024-12-21 19:01 UTC, TimMonko commented on docs/howtos/layers/image.md
> +the other hand, the larger contrast limit corresponds to the value of the image
```suggestion
meaning that in most cases any value under the lower contrast limit will appear as black. On
the other hand, the upper contrast limit corresponds to the value of the image
```

2024-12-21 19:01 UTC, TimMonko commented on docs/howtos/layers/image.md
> +the other hand, the larger contrast limit corresponds to the value of the image
Is it worth using lower/upper language isntead of smaller/larger (there's a few other places this is relevant)? I suppose it's equivalent language, but I do find that perhaps for arrays with signed values lower/upper is more intuitive when I explain to others (because while -2 is smaller than -0.1, the magnitude is larger)

2024-12-21 19:01 UTC, TimMonko commented on docs/howtos/layers/image.md
> +For RGB images, adjusting the contrast limits adjusts the black point and white point of the image.
Should these lines be moved to above the L375 code cell? on the webpage it feels a bit caught out between the image and the admonition

2024-12-23 15:11 UTC, melissawm commented on docs/_static/images/contrast_limits.webm
Yeah - I made two versions, and remembered that we got feedback the other day about GIFs/animations being too quick for the user to see what was happening. Happy to redo if we think this is too much, though!

2025-01-17 12:59 UTC, merged

2025-01-17 13:00 UTC, jni commented on docs/howtos/layers/image.md
> +For RGB images, adjusting the contrast limits adjusts the black point and white point of the image.
@TimMonko I'm trying to get the 0.5.6 release done so I merged with your other two suggestions. If you want to make a PR with this comment we can review that for the next release!