add sample database page
napari/docs pull request #56
Opened 2022-11-22 17:54 UTC by chili-chiu

# Description

Add publicly available (bio)image sample databases as further resources on napari.org.
Also to address [this issue](https://github.com/napari/napari/issues/316) on napari.
 
## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

2022-11-30 22:17 UTC, DragaDoncila requested changes
@chili-chiu I love this so much, just requested minor changes. Keen to have this in 🎉

2022-11-30 22:17 UTC, DragaDoncila commented on docs/further-resources/sample_data.md
> +| **Database**                                               | **URL**                                                                  | **Description**
We need a title here e.g. `# Sample Databases`, as otherwise this won't show up in the TOC. I think we should also add an introductory sentence, even though it's fairly obvious what this is. Also maybe recommending that if people know of other online data repositories they should let us know.

2022-11-30 22:17 UTC, DragaDoncila commented on docs/further-resources/sample_data.md
> +| Allen Brain Atlases                                        | http://portal.brain-map.org                                              | Human and mouse brain atlas containing gene expression, anato
I would personally remove the URL column and just make the database name clickable with the link.

2022-11-30 22:51 UTC, chili-chiu commented
thanks @DragaDoncila, addressed your two questions :)

2022-12-01 01:47 UTC, DragaDoncila approved these changes
Thanks for making those updates @chili-chiu !

2022-12-01 23:18 UTC, merged