[WIP] Updating napari's python and Bundled App Installation Instructions (continued)
napari/docs pull request #74
Opened 2022-12-15 21:02 UTC by jaimergp

# Description

## Type of change

- [X] Fixes or improves existing content
- [ ] Adds new content page(s)
- [ ] Fixes or improves workflow, documentation build or deployment

# References

This PR is bringing https://github.com/napari/napari/pull/4383 over to `napari/docs`. It's not a perfect port, and I had to edit some patches, but it keeps most of the original history.

Inspired by https://github.com/napari/napari/pull/5240#issuecomment-1282076004, I followed these steps:

1. Obtain the commit-by-commit patch from the original PR:

```bash
$ cd ~/devel/napari/napari
$ gh pr checkout 4383
$ gh pr diff --patch > ~/tmp/napari-4383.patch
```

2. Apply patch interactively on `napari/docs`:

```bash
$ cd ~/devel/napari/docs
# Create new branch from up-to-date main
$ git checkout main
$ git pull upstream main
$ git checkout -b bring-napari-4383
# Apply patch
$ git am ~/tmp/napari-4383.patch
```

Sadly, the naive `git am` command with no flags didn't work, so I had to do it "interactively" with `-i --rejected`, which iteratively creates `*.rej` files with the rejected chunks of each patch:

```bash
$ git am -i --rejected ~/tmp/napari-4383.patch
# analyze rejection and modify target file; then:
$ git am -i --rejected --continue
# rinse and repeat til you are done
```

With the ground work here, I'll work on polishing the remaining aspects, updating screenshots, etc. So not ready yet!

Also maybe I messed up some parts of the text, but I'll try my best once I can see the previews.

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added [alt text](https://webaim.org/techniques/alttext/) to new images included in this PR

---

Closes https://github.com/napari/docs/issues/67

2022-12-16 14:58 UTC, jaimergp commented
Loving the `<kbd>` default style!

<img width="965" alt="image" src="https://user-images.githubusercontent.com/2559438/208125823-4d28d699-babb-498c-aeaa-fee696fcc3d5.png">

2024-02-28 22:03 UTC, psobolewskiPhD commented
Gentle reminder about this one @jaimergp Pretty high-value contribution!!
❤️

2024-03-21 08:16 UTC, jaimergp commented
I don't remember what was blocking this, but I think I recall it was something about conveying the right kind of messaging in the website. Are we ok to publish this now? @psobolewskiPhD

2024-03-23 23:06 UTC, psobolewskiPhD commented
@jaimergp I think the bundle was considered experimental? but now it's pretty stable, right?
Anyhow, I think it's definitely something we want in the docs.
Nothing has changed with images, just commit and push.

2024-06-28 15:16 UTC, melissawm commented
Hi all! Is there anything I can do to help push this forward? Cheers! 😄

2024-07-16 12:28 UTC, jaimergp commented
Now that we have 0.5.x out, we can take the screenshots and update the text.

2024-07-16 17:29 UTC, jaimergp commented
@melissawm - do you happen to have a Linux (VM or not) machine for x64? I can only virtualize ARM 😬

2024-07-16 17:56 UTC, melissawm commented
@jaimergp yes I do, happy to help!

2024-07-16 18:06 UTC, jaimergp commented
Excellent, we'd just need to update the screenshots `docs/tutorials/assets/tutorials/installation/bundle_{28..35}.png` with the most recent Linux SH installer at https://github.com/napari/napari/releases/tag/v0.5.0.

2024-07-16 18:12 UTC, melissawm reviewed
Instructions work fine on Manjaro - do you need anything else? Updated screenshots of the viewer? For the terminal screenshots, I think the Ubuntu ones are more common tbh.

EDIT: Got it, will push to this PR in a few mins.

2024-07-16 18:12 UTC, melissawm commented on docs/tutorials/fundamentals/installation_bundle_conda.md
> +Once you have downloaded the Linux SH file, you will have a file with a name like `napari-0.4.15-Linux-x86_64.sh`. You can double-click this file to open the installer in a terminal, or, alternativel
nitpick, but double clicking is not consistent across Linux distros/WM so I'd not even mention that.

2024-07-16 18:15 UTC, jaimergp commented
> Updated screenshots of the viewer?

It's mostly about the version string in the screenshots. Having 0.5.0 looks cleaner than a dev version of 0.4.17 😬

I need to update the text too. I'll take a look at your suggestion, thanks!

2024-07-16 18:32 UTC, melissawm commented
Let me know if you need something different!

2024-07-16 18:40 UTC, jaimergp commented
Looks amazing, thanks @melissawm!

2024-07-18 01:56 UTC, psobolewskiPhD requested changes, later dismissed
This looks super!
Could we get it better integrated with the installation guide?
https://output.circle-artifacts.com/output/job/a8a5e740-214a-47ab-9c56-fed5228432a4/artifacts/0/docs/docs/_build/html/tutorials/fundamentals/installation.html#install-as-a-bundled-app
I think this should be all but dropped and just replaced with a link to the new guide?

2024-07-24 07:37 UTC, jni commented
@jaimergp we just discussed this at community meeting. At a minimum before merge we would like to add a link to this new guide [in this page](https://napari.org/dev/tutorials/fundamentals/installation.html#install-as-a-bundled-app) ([source link](https://github.com/napari/docs/blob/be5bf6c06c5f515c08f16261fb4e3683ea7aea1d/docs/tutorials/fundamentals/installation.md?plain=1#L230)). We are planning to release later today, so if you have a chance to add a small link 🙏 that would be great, otherwise, let us know and we can push directly.

2024-07-24 11:52 UTC, jaimergp commented
How does this look: https://output.circle-artifacts.com/output/job/fb66cbb2-7b72-4b9e-9aa2-4199b5844109/artifacts/0/docs/docs/_build/html/tutorials/fundamentals/installation.html#install-as-a-bundled-app

2024-07-24 12:23 UTC, jni commented
it looks good to me, thanks @jaimergp — I'm just gonna give @psobolewskiPhD a chance to have another look at it, but will just merge in the morning if he doesn't get a chance.

2024-07-25 00:52 UTC, jni approved these changes

2024-07-25 00:57 UTC, merged

2024-07-25 01:16 UTC, psobolewskiPhD commented
Sorry I dropped the ball on this -- long day :sad:

2024-07-25 03:03 UTC, jni commented
all is well @psobolewskiPhD, I just hope I didn't offend you with

<img width="493" alt="Screenshot 2024-07-25 at 1 02 20 PM" src="https://github.com/user-attachments/assets/3a74f373-b38f-436d-a002-77b361988dbc">

😂 🙏